theme: jekyll-theme-minimal
{{ site.time | date_to_string: "ordinal", "US" }}
title: Hi, I’m Stephanie!
description: Feel free to save this page and stay updated on my latest projects. 

I can be contacted at stephanie.fong@berkeley.edu. Cheers!
